os: linux
dist: bionic
language: python
python:
- 3.7
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_56635d5d55b3_key -iv $encrypted_56635d5d55b3_iv -in do_ssh_key.enc -out ssh_keys/do_ssh_key -d
- chmod 600 ssh_keys/do_ssh_key
- echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
- eval "$(ssh-agent -s)"
- DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add ssh_keys/do_ssh_key </dev/null
install:
- docker --version
stages:
- docker_build
- test
- deploy
jobs:
  include:
  - stage: docker_build
    name: build and push docker
    script:
    - echo "LOGIN"
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - echo "BUILD"
    - docker build -t $DOCKER_USERNAME/pythonkindergartenimage:latest . -f Dockerfile
    - echo "PUSH"
    - docker push $DOCKER_USERNAME/pythonkindergartenimage:latest
  - stage: deploy
    name: deploy new version
    if: branch = master
    install: skip
    script: |
      ssh -o "StrictHostKeyChecking no" ${MT_USER}@${MT_SERVER} \
      "cd /vagrant && \
      docker-compose pull && \
      docker-compose up -d && \
      docker pull $DOCKER_USERNAME/pythonkindergartenimage:latest"
