trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml

variables:
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build Server
      inputs:
        command: 'build'
        projects: '**/MiniTwitApi.Server.csproj'


- stage: Release
  displayName: Release stage

  jobs:
  - job: Publish
    displayName: Publishing Artifacts

    pool:
      vmImage: $(vmImageName)

    steps:    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        workingDirectory: '$(System.DefaultWorkingDirectory)/MiniTwitApi'
        