trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml

variables:
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build Server
      inputs:
        command: 'build'
        projects: '**/MiniTwitApi.Server.csproj'


- stage: Release
  displayName: Release stage

  jobs:
  - job: Publish
    displayName: Publishing Artifacts

    pool:
      vmImage: $(vmImageName)

    steps:    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
    
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure til studerende (a52df485-da39-47f1-beac-ac42b035fcba)'
        appType: 'webApp'
        WebAppName: 'PythonKindergarten'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'