version: '3.5'

networks:
  elk:
  main:

volumes:
  elk_elasticsearch_data:

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
    ports:
        - 9200:9200
    environment:
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        - "discovery.type=single-node"
    volumes:
        - elk_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
        - elk

  kibana:
    image: kibana:7.2.0
    ports:
        - 5601:5601
    volumes:
        - ./kibana.yml:/vagrant/database/kibana.yml    
    networks:
        - elk 

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"  
    networks:
      - main