version: '3.3'

networks:
  main:

services:

  minitwitimage:
    image: victornor/pythonkindergartenimage
    container_name: pythonkindergarten
    networks:
      - main
    ports:
        - '80:5000'
        - '443:5001'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - main

  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"  
    networks:
      - main