version: '3.3'

networks:
  main:

services:

  minitwitimage:
    image: ${DOCKER_USERNAME}/pythonkindergartenimage
    container_name: pythonkindergarten
    networks:
      - main
    ports:
        - '5000:5000'
