version: '3.3'

networks:
  main:

services:

  minitwitimage:
    image: victornor/pythonkindergartenimage
    container_name: pythonkindergarten
    networks:
      - main
    ports:
        - '5000:80'
        - '5001:443'
