name: Releasetest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #----------------------------RELEASE------------------------------------
  release:
    # Inspired by https://birtony.medium.com/setting-up-automated-release-workflow-with-github-actions-628dbca2446e
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: currentTime
        with:
          format: YYYYMMDD-HH:MM:SS
          utcOffset: "+02:00"
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          R_TIME: "${{ steps.current-time.outputs.readableTime }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
          YEAR: "${{ steps.current-time.outputs.year }}"
          DAY: "${{ steps.current-time.outputs.day }}"
        run: echo $TIME $R_TIME $F_TIME $YEAR $DAY
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.currentTime.outputs.formattedTime }}"
          release_name: "${{ steps.currentTime.outputs.formattedTime }}"
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
