
name: Latex2PDFManually

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: ./projectreport
        args: "-lualatex -file-line-error -interaction=nonstopmode"
        latexmk_use_lualatex: true
        latexmk_shell_escape: true
    - name: Ls
      run: | 
        ls
        cd projectreport
        ls
    - name: Get current date
      id: date
      run: | 
        echo "::set-output name=date::$(date +'%Y%m%d')"
    - name: Write current date
      run: echo ${{ steps.date.outputs.date }}
    - uses: rymndhng/release-on-push-action@v0.18.0
      with:
        bump_version_scheme: minor
    - name: Update release
      uses: johnwbyrd/update-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./projectreport/main.pdf
