
name: Latex2PDFManually

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: ./projectreport
        args: "-lualatex -file-line-error -interaction=nonstopmode"
        latexmk_use_lualatex: true
        latexmk_shell_escape: true
    - uses: papeloto/action-zip@v1
      with:
        files: ./projectreport
        dest: report.zip
    - id: release
      uses: rymndhng/release-on-push-action@v0.18.0
      with:
        bump_version_scheme: minor
    - name: Check Output Parameters
      run: |
        echo "Got tag name ${{ steps.release.outputs.tag_name }}"
        echo "Got release version ${{ steps.release.outputs.version }}"
    - name: Rename report
      run: |
        cd projectreport
        mv main.pdf report.pdf
    - uses: AButler/upload-release-assets@v2.0
      with:
        files: './projectreport/report.pdf'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ steps.release.outputs.tag_name }}
    - uses: AButler/upload-release-assets@v2.0
      with:
        files: 'report.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ steps.release.outputs.tag_name }}
