
name: Latex2PDFManually

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: ./projectreport
        args: "-lualatex -file-line-error -interaction=nonstopmode"
        latexmk_use_lualatex: true
        latexmk_shell_escape: true
    - name: Ls
      run: | 
        ls
        cd projectreport
        ls
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./projectreport/main.pdf
        prerelease: true
        name: "Report-release"
        tag_name: "report"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
