name: Latex2PDFManually

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: ./projectreport
    - name: Ls
      run: ls
